### PR TITLE
[Bug Fix] Fix space format

### PR DESCRIPTION
**Pull request by Rintim**
To make the commands like `#pkg` become `# pkg`

### CODE REVIEW

**Comment by ykla** [comment]
…没通过冲突检测

**Review by ykla — COMMENTED** [review]
这是啥？

**Review by ykla — APPROVED** [review]

**Review by ykla — CHANGES_REQUESTED** [review]
不应改变目录结构，会造成冲突

**Review by ykla — CHANGES_REQUESTED** [review]
这是在做什么？

**Comment by Rintim** [comment]
Well, it seems like there is something wrong when posted from downstream to upstream
I'm closing this pull request and going to fix the error

**Comment by ykla** [comment]
我已经加好空格了……

**Pull request closed without merging**
